In [1]:
my_list = [1, 3, 4]

In [2]:
import numpy as np
my_array = np.array(my_list)

In [3]:
print my_array

[1 3 4]


In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [6]:
np.arange(5, 4)

array([], dtype=int64)

In [7]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
from __future__ import division

In [9]:
5/3


1.6666666666666667

In [11]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
1/ arr1


array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [18]:
arr1** 3


array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])

In [19]:
arr = np.arange(0, 11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[8]

8

In [22]:
arr[1:5]

array([1, 2, 3, 4])

In [23]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [24]:
arr[0:5] = 100

In [25]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
arr


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr = np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
slice_of_arr = arr[0:5]

In [31]:
slice_of_arr[:] = 99


In [32]:
arr


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [33]:
arr_copy = arr.copy()

In [34]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [35]:
arr2d = np.array(([5,3,6],[1,4,5],[6,7,8]))

In [36]:
arr2d


array([[5, 3, 6],
       [1, 4, 5],
       [6, 7, 8]])

In [37]:
arr2d[0]

array([5, 3, 6])

In [42]:
arr2d[1][1]


4

In [43]:
arr2d[:2,1:]

array([[3, 6],
       [4, 5]])

In [44]:
arr2d[1]

array([1, 4, 5])

Fancy indexing

In [46]:
arr_2d = np.zeros([10,10])

In [47]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [48]:
arr_length = arr_2d.shape[1]

In [49]:
arr_length

10

In [53]:
for i in range(arr_length):
    arr_2d[i] = i

In [54]:
arr_2d


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Using fancy indexing

In [55]:
arr_2d[[2,5,6,7]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])