In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
A = np.random.randn(10)



In [6]:
A


array([ 0.73316534,  0.17960523,  0.89076118, -0.00173585,  0.98702696,
        0.68258568,  1.21769062,  0.37058142,  0.17181848, -0.27670897])

In [12]:
# Binary functions
# Matrix addition
np.add(A,B)

array([ 1.47276936, -1.88989307,  1.19415996, -2.33736707, -0.03383637,
        0.37229675, -1.29899441,  0.19238306, -0.87964997, -1.54405437])

In [10]:
B = np.random.randn(10)

In [11]:
B

array([ 1.89417168, -2.17947998, -0.32279168, -2.34655687,  0.72347006,
        0.77957287, -0.40454142,  1.28589698, -1.32608785, -1.64978746])

In [15]:
np.maximum(A,B)

array([ 1.89417168,  0.28958691,  1.51695164,  0.0091898 ,  0.72347006,
        0.77957287, -0.40454142,  1.28589698,  0.44643788,  0.10573309])

In [16]:
website = "http://www.scipy.org/getting-started.html"
import webbrowser
webbrowser.open(website)

True